plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/user/elie-app/Elie-le-Prophete-Shekinah-VGR"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]